export const dogBreeds = {
  'Labrador Retriever': '라브라도 리트리버',
  'German Shepherd': '저먼 셰퍼드',
  Bulldog: '불독',
  Poodle: '푸들',
  Beagle: '비글',
  Chihuahua: '치와와',
  'Golden Retriever': '골든 리트리버',
  Pug: '퍼그',
  'Siberian Husky': '시베리안 허스키',
  Dachshund: '닥스훈트',
  'Shih Tzu': '시츄',
  'Bichon Frise': '비숑 프리제',
  'Basset Hound': '바셋 하운드',
  'Cocker Spaniel': '코커 스패니얼',
  Pomeranian: '포메라니안',
  Maltese: '말티즈',
  'Yorkshire Terrier': '요크셔 테리어',
  'Miniature Schnauzer': '미니어처 슈나우저',
  'Shetland Sheepdog': '셔틀랜드 쉽독',
  'West Highland White Terrier': '웨스트 하이랜드 화이트 테리어',
  'Border Collie': '보더 콜리',
  'Jack Russell Terrier': '잭 러셀 테리어',
  'Miniature Pinscher': '미니어처 핀셔',
  'Miniature Shiba Inu': '미니어처 시바 이누',
  'American Eskimo Dog': '아메리칸 에스키모 도그',
  'Chesapeake Bay Retriever': '체서피크 베이 리트리버',
  Vizsla: '비즐라',
  'Welsh Corgi': '웰시 코기',
} as const;
